// src/app/types/chart-data.ts

// Represents a single data point for charts (e.g., line or bar charts)
export interface ChartDataPoint {
  date: string; // Date for the data point
  sum: number | string; // Value of the data point (can be a number or a string to be parsed)
}

// Represents data for pie charts
export interface PieChartData {
  source: string; // Source of the data (e.g., "Facebook", "Google")
  orders: number; // Number of orders
  revenue: number; // Revenue generated
  customers: number; // Number of customers
}

// Represents data fetched for charts (line or bar)
export interface ChartData {
  date: string; // Date for the chart data
  sum: number | string; // Value for the chart (number or string to handle flexible APIs)
}

// Metrics data for dashboards (e.g., total sales, orders, growth percentages)
export interface MetricsData {
  totalSales: number; // Total sales in a currency (e.g., USD)
  totalOrders: number; // Total number of orders
  activeUsers: number; // Number of active users
  salesGrowth: number; // Sales growth percentage
  ordersGrowth: number; // Orders growth percentage
  usersGrowth: number; // Users growth percentage
}

// Represents channel data for analytics (e.g., traffic sources)
export interface ChannelData {
  name: string; // Name of the channel (e.g., "Facebook", "Google")
  value: number; // Value for the channel (e.g., revenue or orders)
}

// Revenue data (e.g., for a line chart showing trends)
export interface RevenueData {
  date: string; // Date for the revenue data
  value: number; // Revenue value for the date
}

// Analytics data for age groups
export interface AgeAnalytics {
  age_group: string; // Age group (e.g., "18-24", "25-34")
  orders: number; // Number of orders for the age group
  revenue: number; // Revenue generated by the age group
  avg_order: number; // Average order value for the age group
}

// Response format for age analytics API
export interface AgeAnalyticsResponse {
  data: AgeAnalytics[]; // Array of age analytics data
}

// Analytics data for countries
export interface CountryAnalytics {
  country: string; // Name of the country (e.g., "United States")
  orders: number; // Number of orders from the country
  revenue: number; // Revenue generated from the country
  percentage: number; // Percentage contribution to the total revenue
}

// Response format for country analytics API
export interface CountryAnalyticsResponse {
  data: CountryAnalytics[]; // Array of country analytics data
}
